apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: default
spec:
  selector:
    app: grafana
  ports:
    - name: http  # Name required for the service port
      port: 80
      targetPort: 3000
  type: ClusterIP  # Type of service; ClusterIP makes it accessible within the cluster
