apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    alerting:
      alertmanagers:
        - static_configs:
            - targets:
                - 'alertmanager:9093'  # Alertmanager service (if deployed)

    rule_files:
      - "/etc/prometheus/alert.rules.yml"  # Path to alerting rules

    scrape_configs:
      - job_name: 'nodejs-app'
        static_configs:
          - targets: ['16.171.18.36:3000']  # Replace with your Node.js app service
